### PR TITLE
Better Server Control Area

### PR DESCRIPTION
**Pull request by Dylan3304**
- Changes Start button to green.
- Disables certain buttons when server is offline/online.
- Resolves issue #516

### CODE REVIEW

**Comment by Omeryl** [comment]
I feel, personally, this has the same issues as the other PR you did. Wouldn't it make more sense to have Scales emit a status and go from that?

**Comment by Dylan3304** [comment]
Honestly, hooking into the update server status is better than making a whole new query.

**Comment by Omeryl** [comment]
I didn't say create a new query, rather hook into the already connected websocket connection (with Scales) and just going by what Scales tells us (which would require some work to Scales itself, but would be more reliable and instant vs just spamming a URL endpoint every 5 seconds).

**Comment by Omeryl** [comment]
The idea was sort of even started here:
https://github.com/PufferPanel/PufferPanel/blob/master/app/views/base.html#L57

It just needs a little bit of extending for the other states?

**Comment by Dylan3304** [comment]
Honestly, not really. What would the difference be between offline and stopping stages?

**Comment by Omeryl** [comment]
Wait, ahah, Scales is already advertising starting/stopping/etc then just hook into those.. no need to do this entire little setInterval on a new function.

**Comment by Dylan3304** [comment]
I didn't create `updateServerStatus()`, I just added a little code in it.

**Comment by Omeryl** [comment]
I'm saying, there's a nicer way to do this than what you hacked into what already was there, and that's via the WebSocket connection on the status event.

**Comment by DaneEveritt** [comment]
This is definitely not a good implementation of the status checking. As @Omeryl said, it would be much more efficient, and easier, to just hook into the websocket that is already listening for status events on all pages and update based on that. Obviously on the first page load you'll need to do a check for the status via the URL endpoint, but you shouldn't be checking that URL constantly, especially if the websockets can handle it.

**Comment by Dylan3304** [comment]
Where can I hook into the websocket?

**Comment by DaneEveritt** [comment]
https://github.com/PufferPanel/PufferPanel/blob/master/app/views/node/index.html#L140

Obviously hook into `status` not `stats`

**Pull request closed without merging**
