### PR TITLE
Remove PHP end tags

### PR DESCRIPTION
**Pull request by onbjerg**
Just doing some easy picks.

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Thanks for the PR's, but I'm not going to merge this as we are rewriting the panel in Meteor currently so the master branch isn't really up to date anymore. Check out the `kraken` branch to see where things are happening.

**Comment by onbjerg** [comment]
I see. Why Meteor, though? I've used Meteor for a project once, and I've run into a lot of problems involving security. I've also seen others complain about this.

**Comment by DaneEveritt** [comment]
You'd have to ask @LordRalex or @puffrfish about that since I wasn't around when the decision was made.

**Comment by onbjerg** [comment]
Since an API for Scales is coming (or is pretty much there? #164) it should be able to do it without server-side code at all, using only HTML and Angular.js, provided the security is good.

I'll just wait until they answer, thanks for pinging them :100:

**Comment by DaneEveritt** [comment]
We would still need an API for PufferPanel to handle adding new servers and general management things, it wouldn't be as simple as just implementing the Scales API (which exists in entirety). Personally I wasn't around for the decision to switch to Meteor, or to NodeJS in general for the panel, I still would prefer to have it written in PHP, even if people don't like it. I feel like moving to a new language is just setting us even further back when we could be moving forward with PufferPanel and implementing more features. I mean, I literally spent three months rewriting the entire thing to use Klein and be much cleaner and well rounded, and now we are off rewriting it for the umpteenth time.

**Comment by onbjerg** [comment]
I agree, it seems odd to stagnate the development. PHP is fine. It has it's downsides, but so does every language and platform in existence. Not to mention that rewrites usually introduce new bugs, or old bugs previously closed in master.

**Comment by DaneEveritt** [comment]
Join the IRC channel (irc.esper.net #pufferpanel) for more discussion as well.

**Comment by onbjerg** [comment]
I just did. Had to Google for the IRC, though, could you add it to pufferpanel.com somewhere?

**Pull request closed without merging**
