### PR TITLE
Add "/" to Command Box

### PR DESCRIPTION
**Pull request by BlameDylan**
Some of my new clients were having trouble submitting commands, when all they were doing is putting a "/" in-front of the command, when it isn't needed. So I decided to add it!

### CODE REVIEW

**Comment by Omeryl** [comment]
As cool as it looks, PufferPanel is meant to be game-indepependent and not all games use "/" in their commands.

**Comment by BlameDylan** [comment]
@Omeryl what if I made an `{% if %}` to check if the plugin was Minecraft, would that be acceptable?

**Comment by Omeryl** [comment]
Not really, because Scales isn't appending / to the command though is it? That's just confusing to me imho.

**Comment by puffrfish** [comment]
Sorry, this is not an acceptable way of fixing this even though I recognize the possible issue.

Please open an issue for this instead. Thanks.

**Comment by computerwizjared** [comment]
@BlameDylan Dane said something previously about plugins to the panel, and it seems like this would be something for use in one of those plugins.

**Comment by Omeryl** [comment]
@computerwizjared The biggest issue for things like these is, it's not what'd going on in the underlying UI. I've never seen a panel show a / when it isn't being used internally for the commands, it's just users being silly. Furthermore, we're planning some big changes to 0.9.0 as well and plugins will likely be kept in mind.

**Comment by BlameDylan** [comment]
@Omeryl you think we would be able to make plugins/extensions? I want to make a BukGet plugin so this would work great!

**Comment by Omeryl** [comment]
@BlameDylan not for a while and definitely not in this iteration of PufferPanel.

**Pull request closed without merging**
