### PR TITLE
Bump go-sqlite3 version in go.mod

### PR DESCRIPTION
**Pull request by tie**
This change bumps go-sqlite3 version in go.mod. Note that go-sqlite3 is actually at v1 version, the v2 is [an accident as written in README](https://github.com/gin-contrib/sessions/pull/187).

>Latest stable version is v1.14 or later, not v2.
>
>NOTE: The increase to v2 was an accident. There were no major changes or
>features.

This change fixes an issue described in https://github.com/mattn/go-sqlite3/issues/822

As a side effect, we also upgrade gin-contrib/sessions to the latest commit for https://github.com/gin-contrib/sessions/pull/187 There were no major changes since v0.0.5 release aside from minor dependency version bumps.
https://github.com/gin-contrib/sessions/compare/v0.0.5...189b96f7cac25c37d61aa8b4aa95e79864dd78da

### CODE REVIEW

**Comment by tie** [comment]
@LordRalex, gentle ping, can you take a look at this please?

**Comment by LordRalex** [comment]
Not sure why the bumps for sqlite are needed? That error seems just like a dev warning, and doesn't affect anything in production? 

Not sure why also for go-session a bump is needed.

**Comment by tie** [comment]
>Not sure why the bumps for sqlite are needed? […], and doesn't affect anything in production?

SQLite3 version currently used in PufferPanel is severely outdated, and https://github.com/mattn/go-sqlite3 documentation explicitly states that `v2` tags are an accident and shouldn’t be used.

Theoretically, it shouldn’t affect anything in production, but that’s assuming that SQLite3 usage in PufferPanel is not susceptible to issues solved in newer SQLite3 releases. It’s possible to skim through changes in newer versions and assess whether fixed issues/bugs/vulnerabilities are relevant to PufferPanel, but given that SQLite3 releases are backwards (and usually forward) compatible, I don’t think it’s worth sticking to the old version.

>That error seems just like a dev warning, […]

While it technically is a false positive from C compiler, `go build` fails without workaround mentioned in https://github.com/mattn/go-sqlite3/issues/822#issuecomment-653815573.

>Not sure why also for go-session a bump is needed.

The bump for https://github.com/gin-contrib/sessions is necessary since the latest *tagged* release depends on go-sqlite3 `v2` tag. This was fixed in https://github.com/gin-contrib/sessions/commit/9d780ae7d70a350e0be1c2312065b99ea933bdb2. Unfortunately, there are not tags with this commit. However, there are no changes since the tagged release aside from minor dependency version bumps from dependabot, see https://github.com/gin-contrib/sessions/compare/v0.0.5...189b96f7cac25c37d61aa8b4aa95e79864dd78da, so the bump should be safe.

**Comment by LordRalex** [comment]
> > That error seems just like a dev warning, […]
> 
> While it technically is a false positive from C compiler, `go build` fails (and the error cause is not obvious) without workaround mentioned in [mattn/go-sqlite3#822 (comment)](https://github.com/mattn/go-sqlite3/issues/822#issuecomment-653815573).

It is a warning, and does not fail go build directly. If go build is failing, it is failing for a different reason.

Our entire build pipeline uses go build, and it never has failed because of that issue.

That said, I don't want to just update one dep really, and v3 is where I'd prefer such a large dep upgrade.

**Pull request merged**
