### PR TITLE
Force Master URL to be HTTPS if force secure is set. Fixes #555

### LINKED ISSUE #555: When HTTPS is required, subusers doesnt work
If the setting to require secure is checked, the email sent to a user for them to register as a subuser sends them a link with HTTP instead of HTTPS, causing the link to fail and the user cannot register, but replaceing the HTTP with HTTPS causes it to work.

### PR DESCRIPTION
**Pull request by Omeryl**

### CODE REVIEW

**Comment by BlameDylan** [comment]
Your on a role -- looks great! Thank you for helping you ;)

**Comment by Omeryl** [comment]
Just trying to get this beta on out, @BlameDylan.

**Comment by BlameDylan** [comment]
It is highly anticipated! Think you could take a quick look at [this](https://community.pufferpanel.com/topic/114-enhancements-to-the-server-homepage/#comment-528)?

**Comment by Omeryl** [comment]
@BlameDylan I'm only tackling issues pending this release milestone. 0.9.0 is going to be a rewrite in Meteor more than likely.

**Comment by BlameDylan** [comment]
Got it. @Omeryl you might want to close then re-open this Pull Request, as it looks like Travis CI had an error (not related to your code).

**Comment by Omeryl** [comment]
@BlameDylan I saw, I already told @puffrfish in IRC.

**Comment by puffrfish** [comment]
Thank you so much!

**Pull request merged**
