### PR TITLE
Feature/docker exposure

### PR DESCRIPTION
**Pull request by disconsented**
Allows for resource limits to be imposed in a server.json and allows for properly publishing ports when not using host networking mode.

Which ends up looking like
```javascript
{
  "type": "minecraft-java",
  "data": {
    "eula": {
      "type": "boolean",
      "desc": "Do you (or the server owner) agree to the \u003ca href='https://account.mojang.com/documents/minecraft_eula'\u003eMinecraft EULA?\u003c/a\u003e",
      "display": "EULA Agreement",
      "required": true,
      "value": true
    },
    "ip": {
      "type": "",
      "desc": "What IP to bind the server to",
      "display": "IP",
      "required": true,
      "value": "0.0.0.0"
    },
    "memory": {
      "type": "integer",
      "desc": "How much memory in MB to allocate to the Java Heap",
      "display": "Memory (MB)",
      "required": true,
      "value": 1024
    },
    "motd": {
      "type": "",
      "desc": "This is the message that is displayed in the server list of the client, below the name. The MOTD does support \u003ca href='https://minecraft.gamepedia.com/Formatting_codes' target='_blank'\u003ecolor and formatting codes\u003c/a\u003e.",
      "display": "MOTD message of the day",
      "required": true,
      "value": "A Minecraft Server\\n\\u00A79 hosted on PufferPanel"
    },
    "port": {
      "type": "integer",
      "desc": "What port to bind the server to",
      "display": "Port",
      "required": true,
      "value": 25565
    },
    "version": {
      "type": "",
      "desc": "Version of Minecraft to install",
      "display": "Version",
      "required": true,
      "value": "latest",
      "options": [
        {
          "value": "latest",
          "display": "Latest"
        },
        {
          "value": "1.14.4",
          "display": ""
        },
        {
          "value": "1.12.2",
          "display": ""
        }
      ]
    }
  },
  "display": "Vanilla - Minecraft",
  "environment": {
    "image": "pufferpanel/minecraft",
    "type": "docker",
    "networkMode": "bridge",
    "portBindings": [
      "0.0.0.0:25565:25565/tcp",
      "0.0.0.0:6969:6969/tcp"
    ],
    "resources": {
      "Memory": 5368709120
    },
    "exposedPorts" : {
      "25565/tcp" : {},
      "6969/tcp" : {}
    }
  },
  "install": [
    {
      "target": "server.jar",
      "type": "mojangdl",
      "version": "${version}"
    },
    {
      "target": "server.properties",
      "text": "server-ip=${ip}\nserver-port=${port}\nmotd=${motd}\n",
      "type": "writefile"
    },
    {
      "target": "eula.txt",
      "text": "eula=${eula}",
      "type": "writefile"
    }
  ],
  "id": "28f21f9d",
  "run": {
    "command": "java -Xmx${memory}M -jar server.jar",
    "stop": "stop",
    "autostart": true,
    "autorecover": true
  }
}
```

### CODE REVIEW

**Comment by LordRalex** [comment]
Port bindings do not expose the relevant ports? That's.... annoying

**Comment by LordRalex** [comment]
I hate how we use docker's own object for this, because it doesn't follow how the rest of the JSON works, and also took me ages to find where it's defined (https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/api/types/container/host_config.go#L341)

I guess it can work though.

**Comment by disconsented** [comment]
It's a really strange quirk but in a nutshell yeah, spent a bit of time debugging it last night.

I figure that this is the most _flexible_ way of exposing options and considering how its exposed it doesn't _need_ to be user friendly.

**Comment by LordRalex** [comment]
I think what I would expect is that we would be exposing them probably, nothing says we can't. Although, I guess at that point... we just live with it.

**Pull request merged**
